"""add course id column to students table

Revision ID: 19b8890c446a
Revises: b8a5c4aed376
Create Date: 2024-09-16 10:29:35.413464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b8890c446a'
down_revision: Union[str, None] = 'b8a5c4aed376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students') as batch_op:
        batch_op.add_column(sa.Column('course_id',sa.Integer()))
        batch_op.create_foreign_key('coursesfk','courses', ['course_id'], ['id'])
    # op.add_column('students', sa.Column('course_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'students', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students') as batch_op:
        batch_op.drop_constraint('coursesfk', type_='foreignkey')
        batch_op.drop_column('course_id')
    # op.drop_constraint(None, 'students', type_='foreignkey')
    # op.drop_column('students', 'course_id')
    # ### end Alembic commands ###
