"""add fee column to students table

Revision ID: 70b992d7a357
Revises: 4364abda35ec
Create Date: 2024-09-16 10:10:30.002554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b992d7a357'
down_revision: Union[str, None] = '4364abda35ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'fee')
    # ### end Alembic commands ###
