"""change column fee from integer to string

Revision ID: b8a5c4aed376
Revises: 70b992d7a357
Create Date: 2024-09-16 10:13:01.877950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a5c4aed376'
down_revision: Union[str, None] = '70b992d7a357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students') as batch_op:
        batch_op.alter_column( 'fee',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # op.alter_column('students', 'fee',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students') as batch_op:
        batch_op.alter_column('fee',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # op.alter_column('students', 'fee',
    #            existing_type=sa.String(),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    # ### end Alembic commands ###
